export const mim_avax = {
  address: "0x130966628846BFd36ff31a822705796e8cb8C18D",
  abi: [
    {
      type: "constructor",
      stateMutability: "nonpayable",
      inputs: [
        { type: "string", name: "_name", internalType: "string" },
        { type: "string", name: "_symbol", internalType: "string" },
        { type: "uint8", name: "_decimals", internalType: "uint8" },
        { type: "address", name: "_underlying", internalType: "address" },
        { type: "address", name: "_vault", internalType: "address" },
      ],
    },
    {
      type: "event",
      name: "Approval",
      inputs: [
        {
          type: "address",
          name: "owner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "spender",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "value",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LogAddAuth",
      inputs: [
        {
          type: "address",
          name: "auth",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "timestamp",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LogChangeMPCOwner",
      inputs: [
        {
          type: "address",
          name: "oldOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "effectiveHeight",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LogChangeVault",
      inputs: [
        {
          type: "address",
          name: "oldVault",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newVault",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "effectiveTime",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LogSwapin",
      inputs: [
        {
          type: "bytes32",
          name: "txhash",
          internalType: "bytes32",
          indexed: true,
        },
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "amount",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LogSwapout",
      inputs: [
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "bindaddr",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "amount",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Transfer",
      inputs: [
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: true,
        },
        { type: "address", name: "to", internalType: "address", indexed: true },
        {
          type: "uint256",
          name: "value",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "DOMAIN_SEPARATOR",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "PERMIT_TYPEHASH",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "Swapin",
      inputs: [
        { type: "bytes32", name: "txhash", internalType: "bytes32" },
        { type: "address", name: "account", internalType: "address" },
        { type: "uint256", name: "amount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "Swapout",
      inputs: [
        { type: "uint256", name: "amount", internalType: "uint256" },
        { type: "address", name: "bindaddr", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "TRANSFER_TYPEHASH",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "allowance",
      inputs: [
        { type: "address", name: "", internalType: "address" },
        { type: "address", name: "", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "applyMinter",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "applyVault",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "approve",
      inputs: [
        { type: "address", name: "spender", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "approveAndCall",
      inputs: [
        { type: "address", name: "spender", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "bytes", name: "data", internalType: "bytes" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "balanceOf",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "burn",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "uint256", name: "amount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "changeMPCOwner",
      inputs: [{ type: "address", name: "newVault", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "changeVault",
      inputs: [{ type: "address", name: "newVault", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint8", name: "", internalType: "uint8" }],
      name: "decimals",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "delay",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "delayDelay",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "delayMinter",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "delayVault",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "deposit",
      inputs: [
        { type: "uint256", name: "amount", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "deposit",
      inputs: [{ type: "uint256", name: "amount", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "deposit",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "depositVault",
      inputs: [
        { type: "uint256", name: "amount", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "depositWithPermit",
      inputs: [
        { type: "address", name: "target", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "uint256", name: "deadline", internalType: "uint256" },
        { type: "uint8", name: "v", internalType: "uint8" },
        { type: "bytes32", name: "r", internalType: "bytes32" },
        { type: "bytes32", name: "s", internalType: "bytes32" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "depositWithTransferPermit",
      inputs: [
        { type: "address", name: "target", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "uint256", name: "deadline", internalType: "uint256" },
        { type: "uint8", name: "v", internalType: "uint8" },
        { type: "bytes32", name: "r", internalType: "bytes32" },
        { type: "bytes32", name: "s", internalType: "bytes32" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address[]", name: "", internalType: "address[]" }],
      name: "getAllMinters",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "initVault",
      inputs: [{ type: "address", name: "_vault", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isMinter",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "mint",
      inputs: [
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "amount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "minters",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "mpc",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "name",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "nonces",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "owner",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "pendingDelay",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "pendingMinter",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "pendingVault",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "permit",
      inputs: [
        { type: "address", name: "target", internalType: "address" },
        { type: "address", name: "spender", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "uint256", name: "deadline", internalType: "uint256" },
        { type: "uint8", name: "v", internalType: "uint8" },
        { type: "bytes32", name: "r", internalType: "bytes32" },
        { type: "bytes32", name: "s", internalType: "bytes32" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "revokeMinter",
      inputs: [{ type: "address", name: "_auth", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setMinter",
      inputs: [{ type: "address", name: "_auth", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setVault",
      inputs: [{ type: "address", name: "_vault", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setVaultOnly",
      inputs: [{ type: "bool", name: "enabled", internalType: "bool" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "symbol",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalSupply",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "transfer",
      inputs: [
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "transferAndCall",
      inputs: [
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "bytes", name: "data", internalType: "bytes" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "transferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "transferWithPermit",
      inputs: [
        { type: "address", name: "target", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "value", internalType: "uint256" },
        { type: "uint256", name: "deadline", internalType: "uint256" },
        { type: "uint8", name: "v", internalType: "uint8" },
        { type: "bytes32", name: "r", internalType: "bytes32" },
        { type: "bytes32", name: "s", internalType: "bytes32" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "underlying",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "vault",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "withdraw",
      inputs: [
        { type: "uint256", name: "amount", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "withdraw",
      inputs: [{ type: "uint256", name: "amount", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "withdraw",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "withdrawVault",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "uint256", name: "amount", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
  ],
};
